###########
#  ~/.bash_aliases
#  Additional aliases into a separate file.
###########


# PREFERRED IMPLEMENTATION
# --------------------------------

alias cp='cp -iv '             # Copy files       - (prompt + verbose)
alias grep='grep --color -Ii ' # Preferred search - (ignore binary + ignore case)
alias lal='ls -lFa '           # List content     - (long format with symbol + hidden)
alias less='less -RS '         # File pager       - (raw window + nowrap)
alias ll='ls -lF '             # List content     - (long format with symbol)
alias ln='ln -sf '             # Create a symlink - (symbolink link + force)
alias mkdir='mkdir -pv '       # Make directories - (recursive + verbose)
alias mv='mv -iv '             # Move files       - (prompt + verbose)

alias c='clear'                # Clear terminal display
alias edit='subl '             # Opens any file/folder in Sublime Text editor
alias finder='open -a Finder ' # Opens current directory in MacOS Finder
alias sudo='sudo '             # Allow sudo in aliases comands. - See http://www.shellperson.net/using-sudo-with-an-alias/

alias reload='exec bash -l'


# FILE/FOLDER MANAGEMENT
# --------------------------------

alias remind_chmod_get='# stat -f "%OLp" "filename"'
alias remind_chmod_set='# chmod 644 "filename" / chmod 755 "folder"'
alias remind_find='# find . -type f -name "filename"'
alias remind_rename='# for file in *.txt; do mv "$file" "${file/.txt/.txt.bak}"; done'


# WEB DEVELOPMENT
# --------------------------------

# Packages managers
alias ls_brew='brew ls --versions'
alias ls_gem='gem list --local'
alias ls_npm='npm list --depth=0'
alias ls_bin='ls $GEOJUJI_PATH'

# Edit configuration
alias conf_apache='edit /etc/apache2/httpd.conf /etc/apache2/extra/httpd-vhosts.conf /private/etc/apache2/extra/httpd-ssl.conf'
alias conf_bash='edit ~/.bash_profile ~/.bash_aliases'
alias conf_git='edit ~/.gitconfig ~/.gitaliases ~/.gitignore'
alias conf_hosts='sudo edit /etc/hosts'

# Apache
alias apache_errlogs='less +F /var/log/apache2/dev_error_log'
alias apache_httplogs='tail /var/log/httpd/error_log'
alias apache_restart='sudo apachectl graceful'
alias php_memory='php -d memory_limit=-1'

# MySQL
alias mysql_connect='mysql -u root -p'
