###########
#  ~/.bash_aliases
#  Additional aliases into a separate file.
###########


# PREFERRED IMPLEMENTATION
# --------------------------------

alias cp='cp -iv '                  # Copy files       - (prompt + verbose)
alias grep='grep --color -Ii '      # Preferred search - (ignore binary + ignore case)
alias lal='ls -lFa '                # List content     - (long format with symbol + hidden)
alias less='less -RS '              # File pager       - (raw window + nowrap)
alias ll='ls -lF '                  # List content     - (long format with symbol)
alias ln='ln -sf '                  # Create a symlink - (symbolink link + force)
alias mkdir='mkdir -pv '            # Make directories - (recursive + verbose)
alias mv='mv -iv '                  # Move files       - (prompt + verbose)
alias tail='tail -100f '            # File pager       - (last 100 lines + follow)

alias chmod_get='stat -f "%OLp" '   # Get chmod for "filename"
alias git="LANG=en_US.UTF-8 git";   # Force git to be in english

alias sudo='sudo '                  # Allow sudo in aliases comands. - See http://www.shellperson.net/using-sudo-with-an-alias/
alias c='clear'                     # Clear terminal display
alias reload='exec bash -l'         # Reload bash profile


# WEB DEVELOPMENT
# --------------------------------

# Packages managers
alias ls_brew='brew ls --versions $(brew leaves)'
alias ls_gem='gem list --local'
alias ls_npm='npm list --depth=0'
alias ls_bin='ls -l $GEOJUJI_PATH'
alias npm_allupdate="npm outdated | sed '1d; s/ .*/@latest/' | xargs npm i --save"

# Edit configuration
alias conf_bash='nano ~/.bash_profile ~/.bash_aliases'
alias conf_git='nano ~/.gitconfig ~/.gitaliases ~/.gitignore'
alias conf_hosts='sudo nano /etc/hosts'

# Php / Apache / MySQL
alias apache_conf='sudo nano /etc/apache2/httpd.conf /etc/apache2/extra/httpd-vhosts.conf'
alias apache_restart='sudo apachectl restart'
alias apache_logs='tail -f /var/log/apache2/dev_error_log'
